/**
 * TLCG design note: a warm paper policy page that preserves Verdant Ledger’s
 * editorial hierarchy while keeping legal information readable and restrained.
 */
import { ArrowLeft } from "lucide-react";
import { Link } from "wouter";

const sections = [
  ["Who we are", "Top Line Communications Group operates this website from Johannesburg, South Africa. For the personal information described in this policy, TLCG is the responsible party and is committed to handling information in accordance with the Protection of Personal Information Act 4 of 2013 (POPIA) and other applicable South African requirements."],
  ["Personal information we collect", "We collect the information you choose to provide through the Let’s Talk form: your name, organisation, email address, phone number and message or enquiry information. We do not ask you to submit special personal information through this website. Please do not include sensitive information unless it is necessary for your enquiry."],
  ["How the Let’s Talk form works", "The Let’s Talk form does not send information to a TLCG website database. When you select Send enquiry, your browser prepares an email message addressed to marketing@toplinecommunicationsgroup.co.za using your email application. Once you send that email, TLCG may receive and handle the information in it in order to respond to you."],
  ["Technical and usage information", "The website uses a privacy-focused analytics measurement script to understand aggregate website use and performance. This may process standard technical information generated by your visit, such as pages viewed, referring page, browser or device characteristics, language, screen size and network information that may include an IP address. TLCG does not use this website to collect advertising audiences or to profile visitors for marketing."],
  ["Why we use information", "TLCG uses personal information to respond to enquiries, understand a requested engagement, communicate professionally with you, administer the website and improve its relevance, performance and reliability. We process information where you contact us or ask us to take steps in relation to an enquiry, where it is reasonably necessary for TLCG’s legitimate interests, or where processing is otherwise permitted or required by law."],
  ["Sharing information", "TLCG does not sell personal information. We may share information only where reasonably necessary with technical providers that support website hosting, analytics, email delivery or professional advice, or where disclosure is required for legal compliance, the protection of rights or the management of a valid enquiry. These providers may process limited information on TLCG’s behalf or under their own applicable privacy terms."],
  ["Security and retention", "TLCG takes reasonable technical and organisational steps to protect personal information against unauthorised access, loss, misuse or disclosure. We keep enquiry information only for as long as reasonably needed to respond, manage a potential or existing business relationship, meet legal obligations or resolve a dispute, after which it is deleted or retained only where required by law."],
  ["Your POPIA rights", "Subject to POPIA and applicable law, you may ask TLCG for access to personal information held about you, request correction or deletion where appropriate, object to certain processing, withdraw consent where processing depends on consent, or raise a concern about how your information is handled. You may also have the right to lodge a complaint with the South African Information Regulator."],
  ["Cookies and similar technologies", "The current website configuration does not identify any advertising, social-media or marketing cookies set by TLCG’s page code. Please read our Cookie Policy for the current position on essential technology and the website’s analytics measurement script."],
  ["Changes to this policy", "We may update this Privacy Policy when our website, services or legal requirements change. The updated version will be published on this page with a revised date."],
  ["Important review notice", "This website policy is a working draft based on the current website implementation. It does not replace professional legal advice and should be reviewed by a qualified South African legal adviser for TLCG’s specific processing activities, contracts and compliance obligations before launch."],
] as const;

export default function PrivacyPolicy() {
  return (
    <main className="legal-page">
      <header className="legal-header"><Link href="/" className="legal-back"><ArrowLeft size={16} /> Back to TLCG</Link><span>Top Line Communications Group</span></header>
      <article className="legal-paper">
        <span className="eyebrow">Legal information</span>
        <h1>Privacy<br /><em>Policy.</em></h1>
        <p className="legal-lead">Top Line Communications Group is committed to handling personal information responsibly and transparently, in line with POPIA and applicable South African privacy requirements.</p>
        <div className="legal-meta"><span>Last updated: August 2026</span><span>Johannesburg, South Africa</span></div>
        {sections.map(([title, copy]) => <section key={title}><h2>{title}</h2><p>{copy}</p></section>)}
        <section><h2>Contact us</h2><p>For questions about this policy or personal information, contact Top Line Communications Group at <a href="mailto:hellery@toplinecommunicationsgroup.co.za">hellery@toplinecommunicationsgroup.co.za</a> or <a href="mailto:marketing@toplinecommunicationsgroup.co.za">marketing@toplinecommunicationsgroup.co.za</a>. TLCG is based in Johannesburg, South Africa.</p></section>
      </article>
    </main>
  );
}
